cartesian_limits:
  max_trans_vel: 1.0
  max_trans_acc: 2.25
  # Use positive deceleration magnitude as required by pilz planner and ensure floating-point type
  max_trans_dec: 2.5
  max_rot_vel: 1.57